alias grep="grep --color"
alias ls="ls -G" # color for darwin
alias ll="ls -la"
alias tree="tree -NC" # N: 文字化け対策, C:色をつける
alias vi='vim'
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gio='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'
alias got='git '
alias get='git '
alias catalina='less /usr/local/tomcat/logs/catalina.out'
